/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import controller.*;
import javax.swing.JOptionPane;
import util.*;
import view_table_model.MTableInforme;
/**
 *
 * @author JAIMEUNL
 */
public class main_Frame extends javax.swing.JFrame {

    /**
     * Creates new form main_Frame
     */
    private Informe informe = new Informe();
    private MTableInforme mTableInforme = new MTableInforme();
    private Utiles utiles = new Utiles();
    
    private void cargarTabla(){
        mTableInforme.setInforme(informe);
        tblTablita.setModel(mTableInforme);
        tblTablita.updateUI();
    }
    
    private void crearArreglos(){
        Utiles util = new Utiles();
        String year = yearIndex.getText();
        
        if(year.isEmpty()|| year == null || util.validateInt(year) == false || year.length() > 4 || year.length() < 4){
            JOptionPane.showMessageDialog(null, "Ingrese un valor entero de 4 digitos", "Error", JOptionPane.ERROR_MESSAGE);
            System.out.println("ERROR");
        }else{
            informe.crear();
            btnAgregar.setEnabled(true);
            input_venta.setEnabled(true);
            input_gasto.setEnabled(true);
            box_months.setEnabled(true);
            cargarTabla();
        }
    }
    
    public main_Frame() {
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        input_venta = new javax.swing.JTextField();
        input_gasto = new javax.swing.JTextField();
        box_months = new javax.swing.JComboBox<>();
        btnAgregar = new javax.swing.JButton();
        yearIndex = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTablita = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(920, 650));

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setText("INFORME DE VENTAS ANUALES");
        background.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        input_venta.setBorder(javax.swing.BorderFactory.createTitledBorder("Precio total ventas"));
        input_venta.setEnabled(false);
        input_venta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_ventaActionPerformed(evt);
            }
        });

        input_gasto.setBorder(javax.swing.BorderFactory.createTitledBorder("Precio total gastos"));
        input_gasto.setEnabled(false);

        box_months.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ENERO", "FEBRERO", "MARZO", "ABRIL", "MAYO", "JUNIO", "JULIO", "AGOSTO", "SEPTIEMBRE", "OCTUBRE", "NOVIEMBRE", "DICIEMBRE" }));
        box_months.setBorder(javax.swing.BorderFactory.createTitledBorder("Mes"));
        box_months.setEnabled(false);
        box_months.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box_monthsActionPerformed(evt);
            }
        });

        btnAgregar.setText("Agregar");
        btnAgregar.setEnabled(false);
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        yearIndex.setBorder(javax.swing.BorderFactory.createTitledBorder("Año"));
        yearIndex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearIndexActionPerformed(evt);
            }
        });

        jButton2.setText("Generar Tabla");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(yearIndex, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton2))
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(input_gasto, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAgregar))
                    .addComponent(box_months, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(input_venta, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(592, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yearIndex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(box_months, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(input_venta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(input_gasto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        background.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, -1, -1));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));

        tblTablita.setBackground(new java.awt.Color(255, 255, 255));
        tblTablita.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblTablita);

        background.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 900, 280));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void input_ventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_ventaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_input_ventaActionPerformed

    private void box_monthsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box_monthsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box_monthsActionPerformed
    
    private Boolean verificar(){
        String mes = (String) box_months.getSelectedItem(); //mes

        String ventas = input_venta.getText() != null ? input_venta.getText() : ""; //ventas
        String gastos = input_gasto.getText() != null ? input_gasto.getText() : "";
        if (!ventas.isEmpty() && !gastos.isEmpty()) {
            System.out.println(mes + "\n" + utiles.transformStringFloat(ventas) + "\n" + utiles.transformStringFloat(gastos));
            
            
            return true;
        } else {
            JOptionPane.showMessageDialog(null, "Llene todas las casillas", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }//gastos
    }
    
    private void limpiar() {
        input_venta.setText("");
        input_gasto.setText("");
        //lblpromedio.setText("0.0");
        cargarTabla();
        //fila = -1;
        tblTablita.clearSelection();
    }
    
    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        
        //informe.agregarDato(evt);
        if(verificar()){
            informe.guardarDato(box_months.getSelectedIndex() + 1, input_venta.getText(), input_gasto.getText());
            mTableInforme.actualizarDatos(informe.getData());
            limpiar();
        }
        
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void yearIndexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearIndexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearIndexActionPerformed

    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        informe.crear();
        crearArreglos();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JComboBox<String> box_months;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JTextField input_gasto;
    private javax.swing.JTextField input_venta;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblTablita;
    private javax.swing.JTextField yearIndex;
    // End of variables declaration//GEN-END:variables
}
